/** Every string the client can ask for. A key with no entry here does not compile. */
export const defaultStrings = {
	home: "Home",
	all_projects: "All projects",
	featured: "Featured",
	projects: "Projects",
	appearance: "Appearance",
	theme_system: "System",
	theme_light: "Light",
	theme_dark: "Dark",
	language: "Language",
	details: "Details",
	repository: "Repository",
	stars: "Stars",
	forks: "Forks",
	license: "License",
	languages: "Languages",
	started: "Started",
	last_push: "Last push",
	latest_release: "Latest release",
	translation_missing: "Shown in English",
	locale_unavailable:
		"Your language preference is no longer available. Showing the default language.",
	no_projects_title: "No projects yet",
	no_projects_body: "Nothing has been published to this portfolio.",
	no_sections_title: "No write-up yet",
	no_sections_body:
		"This project has not been described in its repository yet.",
	no_content_title: "Nothing here yet",
	no_content_body: "This page has no sections to show.",
	footer_pages: "Pages",
	footer_elsewhere: "Elsewhere",
	skills_title: "Skills",
	questions_title: "Questions",
	contact_heading: "Get in touch",
	contact_name: "Name",
	contact_email: "Email",
	contact_message: "Message",
	contact_submit: "Send message",
	contact_success: "Thanks — your message is on its way.",
	contact_error: "That did not send. Try again in a moment.",
	skill_familiar: "Familiar",
	skill_proficient: "Proficient",
	skill_expert: "Expert",
	status_wip: "In progress",
	status_active: "Active",
	status_maintenance: "Maintenance",
	status_archived: "Archived",
	not_found_title: "Page not found",
	not_found_body: "This page does not exist, or the project was removed.",
	error_title: "Something went wrong",
	error_body: "The portfolio could not be loaded. Try again in a moment.",
	retry: "Try again",
	go_home: "Back to home",
} as const satisfies Record<string, string>;

export type StringKey = keyof typeof defaultStrings;
