/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSplatRouteImport } from './routes/_shell/$'
import { Route as ShellProjectsIndexRouteImport } from './routes/_shell/projects.index'
import { Route as ShellProjectsSlugRouteImport } from './routes/_shell/projects.$slug'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellProjectsIndexRoute = ShellProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellProjectsSlugRoute = ShellProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => ShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/$': typeof ShellSplatRoute
  '/projects/$slug': typeof ShellProjectsSlugRoute
  '/projects/': typeof ShellProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof ShellSplatRoute
  '/': typeof ShellIndexRoute
  '/projects/$slug': typeof ShellProjectsSlugRoute
  '/projects': typeof ShellProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteRouteWithChildren
  '/_shell/$': typeof ShellSplatRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/projects/$slug': typeof ShellProjectsSlugRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/projects/$slug' | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/projects/$slug' | '/projects'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/$'
    | '/_shell/'
    | '/_shell/projects/$slug'
    | '/_shell/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/$': {
      id: '/_shell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ShellSplatRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/projects/': {
      id: '/_shell/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ShellProjectsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/projects/$slug': {
      id: '/_shell/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ShellProjectsSlugRouteImport
      parentRoute: typeof ShellRouteRoute
    }
  }
}

interface ShellRouteRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProjectsSlugRoute: typeof ShellProjectsSlugRoute
  ShellProjectsIndexRoute: typeof ShellProjectsIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellProjectsSlugRoute: ShellProjectsSlugRoute,
  ShellProjectsIndexRoute: ShellProjectsIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
